<?php 

class PreparedQuery {
	const NEW_USER = "INSERT INTO APPLICANT(EMAIL, PASSWORD_HASH) VALUES(?, ?);";
	const VERIFY_USER = "SELECT APPLICANT_ID, EMAIL FROM APPLICANT WHERE EMAIL=? AND PASSWORD_HASH=?;";
	const GET_APPS = "SELECT * FROM APPLICATION WHERE APPLICANT_ID = ?;";
}

?>